[runtime]
; sampler = polychord
sampler = test
; sampler = fisher
; sampler = nautilus
; sampler = grid
; sampler = emcee
; verbosity = quiet

[DEFAULT]
2PT_FILE = cosmosis-standard-library/likelihood/des-y3/2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate.fits

[pipeline]
modules =  consistency bbn_consistency
           camb
           fits_nz  lens_photoz_width  lens_photoz_bias  source_photoz_bias
           unbiased_galaxies IA ia_z_field
           pk_to_cl_IA
           effective_pk_GGL
           pk_to_cl_GGL
           effective_pk_GC
           pk_to_cl_gg
           J_bin_bias
           b_bin_bias
           add_magnification  add_intrinsic
           2pt_gal  2pt_gal_shear
           shear_m_bias   add_point_mass
           2pt_like
           save_2pt

; quiet=T
timing=T
debug=F
priors = des-y3-maglim-ini-files/des-y3-maglim-priors.ini
values = des-y3-maglim-ini-files/des-y3-maglim-values.ini
; values = des-y3-maglim-ini-files/values_grid.txt
extra_output = cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 data_vector/2pt_chi2
fast_slow = F
first_fast_module = shear_m_bias

[grid]
nsample_dimension = 40

[fisher]
step_size = 0.02
save_fisher_names = T 

[test]
save_dir=output/test
fatal_errors=T

[emcee]
walkers = 70
samples = 300
nsteps = 10

[polychord]
base_dir = output/y3-polychord-checkpoints
polychord_outfile_root = y3
resume = T
feedback = 3
fast_fraction = 0.5

;Very Minimum settings
live_points = 100
num_repeats = 10
tolerance = 10
max_iterations = 500

;;Minimum settings
; live_points = 250
; num_repeats = 30
; tolerance = 0.1

;Settings for paper runs
; live_points = 500
; num_repeats = 60
; tolerance = 0.01
; boost_posteriors = 10.0

[output]
filename = output/des-y3-maglim-2x2pt-polychord.txt
format=text
privacy = F
lock = F

[test]
save_dir=output/des-y3
fatal_errors=T

[consistency];确保输入的宇宙学参数是自洽的
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb_interface.py
mode = power
lmax = 2500          ;max ell to use for cmb calculation
feedback=3         ;amount of output to print
AccuracyBoost=1.1 ;CAMB accuracy boost parameter
do_tensors = T
do_lensing = T
NonLinear = pk
halofit_version = takahashi
zmin_background = 0.
zmax_background = 4.
nz_background = 401
kmin=1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk=700
zmax = 5.

[bbn_consistency];它根据大爆炸核合成 (BBN) 理论，检查重子密度 (Ω_b) 和中微子参数，确保它们在物理上是合理的。
file = cosmosis-standard-library/utility/bbn_consistency/bbn_consistency.py

[fits_nz] ;读取文件，提取 lens 和 source 星系样本的红移分布 n(z)。
file = cosmosis-standard-library/number_density/load_nz_fits/load_nz_fits.py
nz_file = %(2PT_FILE)s
data_sets = lens source
prefix_section = T
prefix_extension = T

[fits_nz_lens];处理光度红移 (photo-z) 的系统误差
file = cosmosis-standard-library/number_density/load_nz_fits/load_nz_fits.py
nz_file = %(2PT_FILE)s
data_sets = lens
prefix_section = T
prefix_extension = T

[lens_photoz_width]
file = cosmosis-standard-library/number_density/photoz_width/photoz_width.py
mode = stretch
sample = nz_lens
bias_section = lens_photoz_errors
interpolation = linear

[lens_photoz_bias]
file = cosmosis-standard-library/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_lens
bias_section = lens_photoz_errors
interpolation = linear

[source_photoz_bias]
file = cosmosis-standard-library/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_source
bias_section = wl_photoz_errors
interpolation = linear

[unbiased_galaxies];一个简单的初始化模块。它暂时将星系偏置 (galaxy bias) 设为1，即假设星系完美地追踪暗物质。这个值在后面会被更复杂的偏置模型覆盖。
file = cosmosis-standard-library/bias/no_bias/no_bias.py

[IA]
file=cosmosis-standard-library/intrinsic_alignments/la_model/linear_alignments_interface.py
do_galaxy_intrinsic=T
method=bk_corrected

[ia_z_field]
file = cosmosis-standard-library/intrinsic_alignments/z_powerlaw/ia_z_powerlaw.py
do_galaxy_intrinsic = T ;计算内禀对齐 (IA) 的幅度随红移的演化。

;这里面包含lens和source，分别表示前景和背景星系样本
[pk_to_cl_IA]
file = cosmosis_modules/project_2d.py
ell_min_logspaced = 0.1
ell_max_logspaced = 5.0e5
n_ell_logspaced = 100
;shear-shear = source-source
;shear-intrinsic = source-source
;intrinsic-intrinsic = source-source
;intrinsicb-intrinsicb=source-source
;lingal-shear = lens-source
lingal-intrinsic = lens-source ;前景星系位置和背景内禀形状之间的交叉相关
lingal-magnification = lens-lens ;前景星系位置和背景放大率之间的交叉相关
magnification-shear = lens-source ;前景星系放大率和背景星系形状之间的交叉相关
magnification-magnification = lens-lens ;前景星系放大率和背景放大率之间的交叉相关
magnification-intrinsic = lens-source ;前景星系放大率和背景内禀形状之间的交叉相关
verbose = F
get_kernel_peaks = F
sig_over_dchi = 20.
shear_kernel_dchi = 10.

[pk_to_cl_gg]
file = cosmosis_modules/project_2d.py
lingal-lingal = lens-lens ;指定lens的角功率谱计算
do_exact = lingal-lingal    ;使用精确的算法计算角功率谱
do_rsd = True ;在计算中使用RSD效应
ell_min_linspaced = 1
ell_max_linspaced = 4
n_ell_linspaced = 5 ;在大尺度上进行5个点的采样
ell_min_logspaced = 5. 
ell_max_logspaced = 5.e5
n_ell_logspaced = 80 ;在小尺度上进行80个点的对数采样
limber_ell_start = 200 ;从200开始的小尺度使用Limber近似
ell_max_logspaced=1.e5
auto_only=lingal-lingal ;只计算自相关，不计算交叉相关
sig_over_dchi_exact = 3.5 ;积分精度

[pk_to_cl_GGL]
file = cosmosis_modules/project_2d.py
ell_min_logspaced = 0.1
ell_max_logspaced = 5.0e5
n_ell_logspaced = 100
;shear-shear = source-source
;shear-intrinsic = source-source
;intrinsic-intrinsic = source-source
;intrinsicb-intrinsicb=source-source
lingal-shear = lens-source ;前景星系位置和背景星系形状之间的交叉相关
;lingal-intrinsic = lens-source
;lingal-magnification = lens-lens
;magnification-shear = lens-source
;magnification-magnification = lens-lens
;magnification-intrinsic = lens-source
verbose = F
get_kernel_peaks = F ;不需要计算并输出透镜核函数 (lensing kernel) 的峰值位置
sig_over_dchi = 20.
shear_kernel_dchi = 10. ;这两个参数控制着沿视线方向进行数值积分时的精度和步长
;执行沿视线方向的积分（投影），计算出各种二维角功率谱 C(ℓ)

[effective_pk_GC];核心修改，其实是把功率谱除掉了sigma8^2，把这一项放到了jhat和bhat里
file = cosmosis_modules/effective_pk_GC.py

[effective_pk_GGL]
file = cosmosis_modules/effective_pk_GGL.py

[J_bin_bias];一个乘法器，用于把红移断层的Jhat乘到角功率谱上
file = cosmosis_modules/J_bin_bias_kstep.py
# 新增的参数，如果是用一种参数化的形式的化
; mg_A = 0       ; 10% 的尺度依赖修正强度
; mg_ell0 = 500.0  ; 转折尺度 l=500
; mg_n = 2.0       ; 二次项增长

[b_bin_bias]
file = cosmosis_modules/b_bin_bias.py
perbin=T
auto_only=T

[add_magnification]
file = cosmosis-standard-library/structure/magnification/add_magnification.py
include_intrinsic=T ;这里是把放大效应加上

[add_intrinsic]
file= cosmosis-standard-library/shear/add_intrinsic/add_intrinsic.py
shear-shear=F
position-shear=T
perbin=F ;这里是把交叉相关和自相关都加上内禀形状影响，得到最终的、包含所有系统效应的理论预测 C(ℓ)_total

[bin_bias]
file = cosmosis-standard-library/bias/binwise_bias/bin_bias.py
perbin=T
auto_only=T

[2pt_gal]
file = cosmosis-standard-library/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type='00'
theta_file=%(2PT_FILE)s
bin_avg = T

[2pt_gal_shear]
file = cosmosis-standard-library/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type='02'
theta_file=%(2PT_FILE)s
bin_avg = T ;进行傅里叶-贝塞尔变换，将角功率谱 (谐空间) 转换成两点相关函数 (实空间)，例如 w(θ) 和 γ_t(θ)

[shear_m_bias]
file = cosmosis-standard-library/shear/shear_bias/shear_m_bias.py
m_per_bin = True
; Despite the parameter name, this can operate on xi as well as C_ell.
;cl_section = shear_xi_plus shear_xi_minus
cross_section = galaxy_shear_xi
verbose = F

[add_point_mass]
file= cosmosis-standard-library/shear/point_mass/add_gammat_point_mass.py
add_togammat = False
use_fiducial = True
sigcrit_inv_section = sigma_crit_inv_lens_source

[2pt_like]
file = cosmosis-standard-library/likelihood/2pt/2pt_point_mass/2pt_point_mass.py
do_pm_marg = True
do_pm_sigcritinv = True
sigma_a = 10000.0
no_det_fac = False
include_norm = True
data_file = %(2PT_FILE)s
data_sets = gammat wtheta
make_covariance=F
covmat_name=COVMAT  ;从其配置中读取观测数据和协方差矩阵的文件路径，将理论预测与观测数据进行比较，计算出卡方

; we put these in a separate file because they are long
%include des-y3-maglim-ini-files/des-y3-maglim-scale-cuts.ini

; This can be used to simulate a data vector from a pipeline
[save_2pt]
file = cosmosis-standard-library/likelihood/2pt/save_2pt.py
theta_min = 2.5
theta_max = 250.0
n_theta = 20
real_space = T
make_covariance = F
shear_nz_name = nz_source
position_nz_name = nz_lens
filename = output/sim_y3.fits
overwrite = T
auto_only = galaxy_xi
;cut_wtheta = 1,2 1,3 2,3 1,4 2,4 3,4 1,5 2,5 3,5 4,5
spectrum_sections = shear_xi_plus shear_xi_minus galaxy_shear_xi galaxy_xi
output_extensions = xip xim gammat wtheta
two_thirds_midpoint = T
copy_covariance=data_vectors/${DATAFILE}
